import type { EvidenceEnvelope, ReleaseProposal, TargetPolicy } from "@/lib/genlayer/types";
import { formatTimestamp, shortHash } from "@/lib/workflow";
import { CopyButton } from "./copy-button";
import { Card, KeyValue, StatusBadge } from "./ui";

function EvidenceCard({ title, evidence, url, evidenceId, authority, policy, proposal, security }: { title: string; evidence?: EvidenceEnvelope; url?: string; evidenceId?: string; authority?: string; policy?: TargetPolicy; proposal: ReleaseProposal; security?: boolean }) {
  const has = Boolean(evidence || url || evidenceId);
  const independent = security ? evidence?.independent_review === true : undefined;
  return <div className="evidence-card"><div style={{ display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" }}><h3>{title}</h3><StatusBadge value={!has ? "MISSING" : evidence ? independent === false ? "REJECTED" : "UNVERIFIED" : "PENDING FETCH"} tone={!has || independent === false ? "missing" : evidence ? "unverified" : "waiting"} /></div><div className="kv-grid" style={{ gridTemplateColumns: "1fr" }}><KeyValue label="Issuer">{evidence?.issuer || authority || "—"}</KeyValue><KeyValue label="Immutable URL" mono><span className="copy-line"><span title={url}>{url ? shortHash(url, 16) : "—"}</span>{url && <CopyButton value={url} />}</span></KeyValue><KeyValue label="Evidence ID" mono>{evidence?.evidence_id || evidenceId || "—"}</KeyValue><KeyValue label="Target binding" mono>{shortHash(evidence?.target || proposal.target)}</KeyValue><KeyValue label="Parent SHA-256" mono>{shortHash(evidence?.parent_sha256 || proposal.parent_code_hash)}</KeyValue><KeyValue label="Candidate SHA-256" mono>{shortHash(evidence?.candidate_sha256 || proposal.candidate_code_hash)}</KeyValue><KeyValue label="Policy binding" mono>{shortHash(evidence?.policy_fingerprint || proposal.policy_fingerprint)}</KeyValue><KeyValue label="Published / expires">{evidence ? `${formatTimestamp(evidence.published_at)} / ${formatTimestamp(evidence.expires_at)}` : "Awaiting authenticated artifact"}</KeyValue>{security && <KeyValue label="Publisher independence">{evidence ? (independent ? "Declared independent — verify publisher identity" : "Not independent") : "Independent publisher required"}</KeyValue>}</div></div>;
}

export function EvidenceCards({ proposal, policy, envelopes }: { proposal: ReleaseProposal; policy?: TargetPolicy; envelopes?: Partial<Record<"source" | "ci" | "security", EvidenceEnvelope>> }) {
  return <div className="evidence-grid"><EvidenceCard title="SOURCE" evidence={envelopes?.source} url={proposal.candidate_source_url} authority={policy?.source_authority} policy={policy} proposal={proposal} /><EvidenceCard title="CI" evidence={envelopes?.ci} url={proposal.ci_evidence_url} evidenceId={proposal.ci_evidence_id} authority={policy?.ci_authority} policy={policy} proposal={proposal} /><EvidenceCard title="SECURITY REVIEW" evidence={envelopes?.security} url={proposal.security_evidence_url} evidenceId={proposal.security_evidence_id} authority={policy?.security_authority} policy={policy} proposal={proposal} security /></div>;
}
