"use client";

import { useQuery } from "@tanstack/react-query";
import { Check, ChevronLeft, ChevronRight, Download, FileCheck2, LockKeyhole, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { getSentinelXConfig, isAddress } from "@/lib/genlayer/chains";
import { loadMeasuredFeeProfile } from "@/lib/genlayer/fees";
import { getActiveProposal, getTargetPolicy } from "@/lib/genlayer/reads";
import type { EvidenceEnvelope, TargetPolicy } from "@/lib/genlayer/types";
import { SEMANTIC_FIELDS } from "@/lib/genlayer/types";
import { deriveApproval, proposalPreconditions, sha256Hex, validateImmutableGitHubUrl, shortHash, formatTimestamp } from "@/lib/workflow";
import { CopyButton } from "./copy-button";
import { SemanticMatrix } from "./semantic-matrix";
import { Card, KeyValue, Notice, PageHeader, StatusBadge } from "./ui";

const STEPS = ["Target", "Candidate", "Evidence", "Preflight", "Freeze"];

export function ReleaseWizard() {
  const config = getSentinelXConfig(); const [step, setStep] = useState(0); const [target, setTarget] = useState(config.canonicalTargetAddress || ""); const [candidateVersion, setCandidateVersion] = useState("2.0.0-safe"); const [sourceUrl, setSourceUrl] = useState(""); const [releaseIntent, setReleaseIntent] = useState("Add the verified release status read without changing user rights or upgrade authority."); const [candidateHash, setCandidateHash] = useState(""); const [sourceSize, setSourceSize] = useState<number>(); const [sourceError, setSourceError] = useState(""); const [ciUrl, setCiUrl] = useState(""); const [ciId, setCiId] = useState(""); const [securityUrl, setSecurityUrl] = useState(""); const [securityId, setSecurityId] = useState(""); const [ciEvidence, setCiEvidence] = useState<EvidenceEnvelope>(); const [securityEvidence, setSecurityEvidence] = useState<EvidenceEnvelope>(); const [evidenceError, setEvidenceError] = useState("");
  const [now] = useState(() => Date.now() / 1000);
  const policyQuery = useQuery({ queryKey: ["wizard-policy", target], queryFn: () => getTargetPolicy(target), enabled: isAddress(target) && config.status === "configured" });
  const activeQuery = useQuery({ queryKey: ["wizard-active", target], queryFn: () => getActiveProposal(target), enabled: isAddress(target) && config.status === "configured" });
  const feeQuery = useQuery({ queryKey: ["measured-fee-profile"], queryFn: loadMeasuredFeeProfile, retry: false });
  const policy: TargetPolicy | undefined = policyQuery.data;
  const preconditions = proposalPreconditions({ configured: config.status === "configured", policyActive: Boolean(policy?.active), activeProposal: activeQuery.data || 0, candidateAlreadyInstalled: Boolean(policy?.current_code_hash && candidateHash && policy.current_code_hash === candidateHash), candidateHash });
  const sourceCheck = validateImmutableGitHubUrl(sourceUrl, policy?.source_prefix);
  const securityIndependent = Boolean(securityEvidence?.independent_review === true && securityEvidence.issuer && securityEvidence.issuer !== policy?.source_authority && securityEvidence.issuer !== policy?.ci_authority);
  const evidenceBindings = useMemo(() => { const all = [ciEvidence, securityEvidence]; return all.every((e) => e && e.target === target && e.parent_sha256 === policy?.current_code_hash && e.candidate_sha256 === candidateHash && e.policy_fingerprint === policy?.policy_fingerprint && e.expires_at > now); }, [candidateHash, ciEvidence, now, policy, securityEvidence, target]);
  const distinctEvidenceIds = Boolean(ciId && securityId && ciId !== securityId && ciEvidence?.evidence_id === ciId && securityEvidence?.evidence_id === securityId);
  const localChecks = [sourceCheck.valid, Boolean(candidateHash), Boolean(ciEvidence), Boolean(securityEvidence), evidenceBindings, distinctEvidenceIds, securityIndependent];
  const localReady = localChecks.every(Boolean);

  async function fetchCandidate() { setSourceError(""); setCandidateHash(""); const check = validateImmutableGitHubUrl(sourceUrl, policy?.source_prefix); if (!check.valid) { setSourceError(check.reason || "Invalid immutable source URL"); return; } try { const response = await fetch(sourceUrl, { cache: "no-store" }); if (!response.ok) throw new Error(`source fetch failed (${response.status})`); const bytes = await response.arrayBuffer(); setSourceSize(bytes.byteLength); setCandidateHash(await sha256Hex(bytes)); } catch (error) { setSourceError(String(error)); } }
  async function fetchEvidence(kind: "ci" | "security") { const url = kind === "ci" ? ciUrl : securityUrl; setEvidenceError(""); if (!url) { setEvidenceError(`${kind.toUpperCase()} evidence URL is required`); return; } try { const response = await fetch(url, { cache: "no-store" }); if (!response.ok) throw new Error(`evidence fetch failed (${response.status})`); const value = await response.json() as EvidenceEnvelope; if (kind === "ci") setCiEvidence(value); else setSecurityEvidence(value); } catch (error) { setEvidenceError(String(error)); } }
  const next = () => setStep((value) => Math.min(4, value + 1)); const back = () => setStep((value) => Math.max(0, value - 1));
  return <div className="page"><PageHeader eyebrow="Release control / New release" title="Freeze a candidate release" description="A release becomes actionable only after exact bytes, authenticated evidence, semantic review and finality requirements are satisfied." /><div className="wizard-steps" aria-label="Release wizard progress">{STEPS.map((label, index) => <div className={`wizard-step ${index === step ? "current" : ""} ${index < step ? "done" : ""}`} key={label}><span className="step-number">{index < step ? <Check size={12} /> : index + 1}</span><span>{label}</span></div>)}</div><Card>{step === 0 && <StepTarget target={target} setTarget={setTarget} config={config} policy={policy} policyLoading={policyQuery.isLoading} active={activeQuery.data || 0} />}{step === 1 && <StepCandidate version={candidateVersion} setVersion={setCandidateVersion} url={sourceUrl} setUrl={setSourceUrl} intent={releaseIntent} setIntent={setReleaseIntent} policy={policy} hash={candidateHash} sourceSize={sourceSize} sourceError={sourceError} onFetch={fetchCandidate} sourceCheck={sourceCheck} />}{step === 2 && <StepEvidence ciUrl={ciUrl} setCiUrl={setCiUrl} ciId={ciId} setCiId={setCiId} securityUrl={securityUrl} setSecurityUrl={setSecurityUrl} securityId={securityId} setSecurityId={setSecurityId} ciEvidence={ciEvidence} securityEvidence={securityEvidence} onFetch={fetchEvidence} error={evidenceError} target={target} policy={policy} candidateHash={candidateHash} independent={securityIndependent} />}{step === 3 && <StepPreflight checks={localChecks} ready={localReady} vector={undefined} />}{step === 4 && <StepFreeze target={target} policy={policy} version={candidateVersion} sourceUrl={sourceUrl} candidateHash={candidateHash} intent={releaseIntent} ciId={ciId} securityId={securityId} preconditions={preconditions} feeProfileAvailable={Boolean(feeQuery.data)} />}{<div className="wizard-actions"><button className="button ghost" onClick={back} disabled={step === 0}><ChevronLeft size={14} />Back</button><div className="wizard-actions-right">{step < 4 ? <button className="button primary" onClick={next} disabled={step === 0 ? !isAddress(target) || !policy?.active || Boolean(activeQuery.data) : step === 1 ? !candidateHash || !sourceCheck.valid : step === 2 ? !ciUrl || !securityUrl : !localReady}>Continue <ChevronRight size={14} /></button> : <button className="button primary" disabled title="Canonical writes are disabled in Phase 2B until deployment and independent security evidence are complete."><LockKeyhole size={14} />FREEZE &amp; SUBMIT RELEASE</button>}</div></div>}</Card></div>;
}

function StepTarget({ target, setTarget, config, policy, policyLoading, active }: { target: string; setTarget: (value: string) => void; config: ReturnType<typeof getSentinelXConfig>; policy?: TargetPolicy; policyLoading: boolean; active: number }) {
  return <div className="page-grid"><div><div className="section-kicker">Step 01 / Target</div><h2 className="card-title">Choose a registered protected contract</h2><p className="card-subtitle">The governor must prove the target, policy and active-proposal preconditions before a candidate can be frozen.</p></div><div className="field"><label htmlFor="target">Target address</label><input id="target" className="mono" value={target} onChange={(e) => setTarget(e.target.value)} placeholder="0x…" /><small>Canonical target addresses are supplied from the environment; none are assumed.</small></div>{config.status !== "configured" && <Notice title="Deployment not configured" tone="warning">Governor and target addresses are not available yet. The independent security publisher is still a prerequisite for canonical registration.</Notice>}{policyLoading && <div className="skeleton" />}{policy && <div className="kv-grid"><KeyValue label="Project">{policy.project_name}</KeyValue><KeyValue label="Current version">{policy.current_version}</KeyValue><KeyValue label="Current code hash" mono>{shortHash(policy.current_code_hash)}</KeyValue><KeyValue label="Active proposal">{active || "none"}</KeyValue></div>}{policy && !policy.active && <Notice title="Target policy inactive" tone="error">This target cannot accept a proposal.</Notice>}{policy && active > 0 && <Notice title="Active proposal collision" tone="error">Resolve or expire proposal #{active} before creating another.</Notice>}</div>;
}

function StepCandidate({ version, setVersion, url, setUrl, intent, setIntent, policy, hash, sourceSize, sourceError, onFetch, sourceCheck }: { version: string; setVersion: (v: string) => void; url: string; setUrl: (v: string) => void; intent: string; setIntent: (v: string) => void; policy?: TargetPolicy; hash: string; sourceSize?: number; sourceError: string; onFetch: () => void; sourceCheck: ReturnType<typeof validateImmutableGitHubUrl> }) {
  return <div className="page-grid"><div><div className="section-kicker">Step 02 / Candidate</div><h2 className="card-title">Identify exact candidate bytes</h2><p className="card-subtitle">Branch names, mutable refs, aliases and path manipulation are not accepted.</p></div><div className="form-grid"><div className="field"><label htmlFor="candidate-version">Candidate version</label><input id="candidate-version" value={version} onChange={(e) => setVersion(e.target.value)} /></div><div className="field"><label>Parent version / hash</label><div className="notice info"><span className="mono">{policy?.current_version || "—"} · {shortHash(policy?.current_code_hash)}</span></div></div><div className="field span-2"><label htmlFor="source-url">Immutable source URL</label><input id="source-url" className="mono" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://raw.githubusercontent.com/owner/repo/<40-char-commit>/path" /><small>{sourceCheck.valid ? `Commit ${sourceCheck.commit} · ${sourceCheck.owner}/${sourceCheck.repository}` : sourceCheck.reason || "Required"}</small></div><div className="field span-2"><button className="button ghost" onClick={onFetch} disabled={!sourceCheck.valid}><Download size={14} />Retrieve and hash candidate</button>{sourceError && <div className="notice error"><ShieldAlert size={15} />{sourceError}</div>}</div><div className="field span-2"><label htmlFor="release-intent">Release intent</label><textarea id="release-intent" value={intent} onChange={(e) => setIntent(e.target.value)} /></div></div>{hash && <div className="notice info"><FileCheck2 size={16} /><div><strong>Candidate frozen locally</strong><div className="mono">SHA-256 {hash}</div><div className="dim">{sourceSize?.toLocaleString()} bytes · fetch result is not GenLayer consensus</div></div><CopyButton value={hash} label="Copy candidate hash" /></div>}</div>;
}

function EvidenceStatus({ title, url, evidenceId, evidence, onFetch, independent }: { title: string; url: string; evidenceId: string; evidence?: EvidenceEnvelope; onFetch: () => void; independent?: boolean }) {
  return <div className="evidence-card"><h3>{title}</h3><div className="field"><label>Immutable artifact URL</label><input className="mono" value={url} readOnly /></div><div className="field" style={{ marginTop: 10 }}><label>Evidence ID</label><input className="mono" value={evidenceId} readOnly /></div><button className="button ghost" style={{ marginTop: 12 }} onClick={onFetch} disabled={!url}>Fetch and validate</button>{evidence ? <div style={{ marginTop: 12 }}><StatusBadge value="FETCHED · BINDINGS PENDING" tone="unverified" /><div className="dim" style={{ marginTop: 6 }}>Issuer: {evidence.issuer || "—"}<br />Candidate: {shortHash(evidence.candidate_sha256)}<br />Expires: {formatTimestamp(evidence.expires_at)}{independent !== undefined && <><br />Independent declaration: {independent ? "yes — identity still requires verification" : "no"}</>}</div></div> : <div className="dim" style={{ marginTop: 12 }}>No artifact fetched. Missing evidence is not replaced with a local fixture.</div>}</div>;
}

function StepEvidence({ ciUrl, setCiUrl, ciId, setCiId, securityUrl, setSecurityUrl, securityId, setSecurityId, ciEvidence, securityEvidence, onFetch, error, target, policy, candidateHash, independent }: { ciUrl: string; setCiUrl: (v: string) => void; ciId: string; setCiId: (v: string) => void; securityUrl: string; setSecurityUrl: (v: string) => void; securityId: string; setSecurityId: (v: string) => void; ciEvidence?: EvidenceEnvelope; securityEvidence?: EvidenceEnvelope; onFetch: (kind: "ci" | "security") => void; error: string; target: string; policy?: TargetPolicy; candidateHash: string; independent: boolean }) {
  return <div className="page-grid"><div><div className="section-kicker">Step 03 / Evidence</div><h2 className="card-title">Bind and authenticate release evidence</h2><p className="card-subtitle">Evidence must bind the exact target, parent, candidate and policy. Authentication happens before semantic adjudication.</p></div><div className="evidence-grid"><div className="evidence-card"><h3>CI EVIDENCE</h3><div className="field"><label htmlFor="ci-url">Immutable CI evidence URL</label><input id="ci-url" className="mono" value={ciUrl} onChange={(e) => setCiUrl(e.target.value)} placeholder={policy?.ci_prefix || "https://…"} /></div><div className="field" style={{ marginTop: 10 }}><label htmlFor="ci-id">Evidence ID</label><input id="ci-id" className="mono" value={ciId} onChange={(e) => setCiId(e.target.value)} /></div><button className="button ghost" style={{ marginTop: 12 }} onClick={() => onFetch("ci")} disabled={!ciUrl}>Fetch and validate</button>{ciEvidence && <div className="dim" style={{ marginTop: 10 }}>Fetched issuer: {ciEvidence.issuer}<br />Target binding: {ciEvidence.target === target ? "match" : "mismatch"}<br />Candidate binding: {ciEvidence.candidate_sha256 === candidateHash ? "match" : "mismatch"}</div>}</div><div className="evidence-card"><h3>SECURITY REVIEW</h3><div className="field"><label htmlFor="security-url">Independent immutable URL</label><input id="security-url" className="mono" value={securityUrl} onChange={(e) => setSecurityUrl(e.target.value)} placeholder={policy?.security_prefix || "https://…"} /></div><div className="field" style={{ marginTop: 10 }}><label htmlFor="security-id">Evidence ID</label><input id="security-id" className="mono" value={securityId} onChange={(e) => setSecurityId(e.target.value)} /></div><button className="button ghost" style={{ marginTop: 12 }} onClick={() => onFetch("security")} disabled={!securityUrl}>Fetch and validate</button>{securityEvidence ? <div className="dim" style={{ marginTop: 10 }}>Fetched issuer: {securityEvidence.issuer}<br />Verdict: {securityEvidence.verdict || "—"}<br />Independent declaration: {independent ? "yes — publisher identity must still be verified" : "missing or not independent"}</div> : <div className="notice warning" style={{ marginTop: 10 }}><ShieldAlert size={15} />Independent security evidence is required.</div>}</div></div>{error && <Notice title="Evidence fetch failed" tone="error">{error}</Notice>}<div className="notice info"><div><strong>Target and policy bindings</strong><div className="mono">{target || "—"} · {shortHash(policy?.policy_fingerprint)} · {shortHash(candidateHash)}</div></div></div></div>;
}

function StepPreflight({ checks, ready, vector }: { checks: boolean[]; ready: boolean; vector?: never }) {
  return <div className="page-grid"><div><div className="section-kicker">Step 04 / Preflight</div><h2 className="card-title">Review deterministic gates</h2><p className="card-subtitle">This screen is a local input check. It is not GenLayer validator consensus and cannot authorize a release.</p></div><Notice title="LOCAL PREFLIGHT — NOT GENLAYER CONSENSUS" tone="warning">Semantic judgment remains NOT REVIEWED until the governor’s nondeterministic review reaches finality.</Notice><div className="matrix">{["Immutable candidate URL", "Candidate hash available", "CI artifact fetched", "Security artifact fetched", "All evidence bindings match", "Distinct evidence IDs", "Independent security declaration"].map((label, index) => <div className="matrix-row" key={label}><span className="matrix-name">{label}</span><StatusBadge value={checks[index] ? "PASS" : "NOT READY"} tone={checks[index] ? "pass" : "not-reviewed"} /></div>)}</div><Card title="14-field semantic vector" subtitle="No local confidence score or partial approval is shown."><SemanticMatrix vector={vector} /></Card><div className={`notice ${ready ? "info" : "warning"}`}><strong>{ready ? "Inputs are ready for freeze" : "Inputs are not ready"}</strong><div>All authorization-driving booleans remain unresolved locally.</div></div></div>;
}

function StepFreeze({ target, policy, version, sourceUrl, candidateHash, intent, ciId, securityId, preconditions, feeProfileAvailable }: { target: string; policy?: TargetPolicy; version: string; sourceUrl: string; candidateHash: string; intent: string; ciId: string; securityId: string; preconditions: { ok: boolean; reasons: string[] }; feeProfileAvailable: boolean }) {
  return <div className="page-grid"><div><div className="section-kicker">Step 05 / Freeze</div><h2 className="card-title">Confirm immutable release fields</h2><p className="card-subtitle">Once submitted, target, parent hash, candidate bytes/hash and policy fingerprint cannot be repaired. Only evidence metadata has a repair path.</p></div><div className="freeze-list">{[["Target", target], ["Parent version", policy?.current_version || "—"], ["Parent SHA-256", policy?.current_code_hash || "—"], ["Candidate version", version], ["Candidate source", sourceUrl], ["Candidate SHA-256", candidateHash], ["Policy fingerprint", policy?.policy_fingerprint || "—"], ["CI evidence ID", ciId], ["Security evidence ID", securityId], ["Release intent", intent]].map(([label, value]) => <div className="freeze-row" key={label}><b>{label}</b><span>{value || "—"}</span></div>)}</div>{!preconditions.ok && <Notice title="Write disabled by preconditions" tone="warning"><ul style={{ margin: 0, paddingLeft: 18 }}>{preconditions.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></Notice>}{!feeProfileAvailable && <Notice title="Measured fee profile not configured" tone="info">Development writes can use a live network-default quote or the explicit concrete-write simulation helper. Production policy may still require measured coverage for high-consequence operations.</Notice>}<Notice title="Phase 2B write gate" tone="info">Canonical chain writes are intentionally disabled in this phase while the independent security publisher and measured profiling prerequisites remain outstanding.</Notice></div>;
}
