"use client";

import { CheckCircle2, CircleOff, ExternalLink } from "lucide-react";
import { configurationSummary } from "@/lib/genlayer/client";
import { feeConfigurationSummary } from "@/lib/genlayer/fees";
import { Card, KeyValue, PageHeader, StatusBadge } from "./ui";

export function SettingsPage() {
  const config = configurationSummary(); const fees = feeConfigurationSummary();
  return <div className="page"><PageHeader eyebrow="Workspace / Settings" title="Network and wallet" description="SentinelX is explicitly configured for Studio-dev. Addresses and fee profiles are supplied through environment configuration." /><div className="page-grid grid-2"><Card title="Network configuration" subtitle="Read-only runtime configuration"><div className="kv-grid"><KeyValue label="Network">studio-dev</KeyValue><KeyValue label="Chain ID" mono>61997</KeyValue><KeyValue label="RPC" mono>{config.rpcUrl}</KeyValue><KeyValue label="Configuration status"><StatusBadge value={config.status} tone={config.status === "configured" ? "verified" : "waiting"} /></KeyValue><KeyValue label="Governor" mono>{config.governorAddress || "Deployment not configured"}</KeyValue><KeyValue label="Canonical target" mono>{config.canonicalTargetAddress || "Deployment not configured"}</KeyValue></div></Card><Card title="Fee controls" subtitle="Fee quantities are never hardcoded"><div className="kv-grid"><KeyValue label="Measured profile"><StatusBadge value={fees.configured ? "CONFIGURED" : "NOT CONFIGURED"} tone={fees.configured ? "verified" : "waiting"} /></KeyValue><KeyValue label="Profile source">{config.feeProfileUrl || "No profile URL configured"}</KeyValue><KeyValue label="Write mode">Disabled in Phase 2B</KeyValue><KeyValue label="SDK">genlayer-js 2.0.0-rc.1</KeyValue></div></Card></div><div style={{ marginTop: 14 }}><Card title="Operator checklist"><div className="matrix"><div className="matrix-row"><span className="matrix-name">Studio-dev endpoint selected</span><StatusBadge value="PASS" tone="pass" /></div><div className="matrix-row"><span className="matrix-name">Canonical deployment proven</span><StatusBadge value="PENDING" tone="pending" /></div><div className="matrix-row"><span className="matrix-name">Independent security publisher</span><StatusBadge value="REQUIRED" tone="waiting" /></div><div className="matrix-row"><span className="matrix-name">Frontend fixture fallback in production</span><StatusBadge value="PROHIBITED" tone="pass" /></div></div><a className="button ghost" href="https://github.com/GIFTEDLOV/sentinelx/tree/7e3b552c8b0471db0411206fdbc743dd12ef4e80/docs" target="_blank" rel="noreferrer" style={{ marginTop: 15 }}><ExternalLink size={13} />Read architecture docs</a></Card></div><div className="notice info" style={{ marginTop: 14 }}><CheckCircle2 size={16} /><div><strong>Wallet is non-custodial</strong><div>Connect a browser wallet from the header when an authorized, configured write is available. The current phase does not broadcast chain transactions.</div></div></div></div>;
}
