"use client";

import { CheckCircle2, ExternalLink } from "lucide-react";
import { configurationSummary } from "@/lib/genlayer/client";
import { feeConfigurationSummary } from "@/lib/genlayer/fees";
import { Card, KeyValue, PageHeader, StatusBadge } from "./ui";

export function SettingsPage() {
  const config = configurationSummary();
  const fees = feeConfigurationSummary();
  return <div className="page"><PageHeader eyebrow="Workspace / Settings" title="Network and wallet" description="SentinelX is explicitly configured for Studionet. Addresses and optional fee-profile coverage are supplied through environment configuration." /><div className="page-grid grid-2"><Card title="Network configuration" subtitle="Read-only runtime configuration"><div className="kv-grid"><KeyValue label="Network">studionet</KeyValue><KeyValue label="Chain ID" mono>61999</KeyValue><KeyValue label="RPC" mono>{config.rpcUrl}</KeyValue><KeyValue label="Configuration status"><StatusBadge value={config.status} tone={config.status === "configured" ? "verified" : "waiting"} /></KeyValue><KeyValue label="Governor" mono>{config.governorAddress || "Deployment not configured"}</KeyValue><KeyValue label="Canonical target" mono>{config.canonicalTargetAddress || "Deployment not configured"}</KeyValue></div></Card><Card title="Fee controls" subtitle="Fee quantities are never hardcoded"><div className="kv-grid"><KeyValue label="Measured profile"><StatusBadge value={fees.configured ? "CONFIGURED" : "OPTIONAL"} tone={fees.configured ? "verified" : "waiting"} /></KeyValue><KeyValue label="Profile source">{config.feeProfileUrl || "No profile URL configured"}</KeyValue><KeyValue label="Write quote">Live SDK/network-default or measured profile</KeyValue><KeyValue label="Dev simulation">Explicit concrete-write estimator</KeyValue><KeyValue label="Gasless mode">Determined from live estimate</KeyValue><KeyValue label="SDK">genlayer-js 1.1.8</KeyValue></div></Card></div><div style={{ marginTop: 14 }}><Card title="Operator checklist"><div className="matrix"><div className="matrix-row"><span className="matrix-name">Studionet endpoint selected</span><StatusBadge value="PASS" tone="pass" /></div><div className="matrix-row"><span className="matrix-name">Canonical V2 deployment proven</span><StatusBadge value="PENDING" tone="pending" /></div><div className="matrix-row"><span className="matrix-name">Security attestation mode</span><StatusBadge value="OPTIONAL or REQUIRED_INDEPENDENT" tone="info" /></div><div className="matrix-row"><span className="matrix-name">High-consequence writes</span><StatusBadge value="DISABLED" tone="waiting" /></div><div className="matrix-row"><span className="matrix-name">Frontend fixture fallback in production</span><StatusBadge value="PROHIBITED" tone="pass" /></div></div><a className="button ghost" href="https://github.com/GIFTEDLOV/sentinelx/tree/main/docs" target="_blank" rel="noreferrer" style={{ marginTop: 15 }}><ExternalLink size={13} />Read architecture docs</a></Card></div><div className="notice info" style={{ marginTop: 14 }}><CheckCircle2 size={16} /><div><strong>Wallet is non-custodial</strong><div>Connect a browser wallet from the header when an authorized, configured write is available. The estimator hierarchy remains usable before fee-profile coverage is complete.</div></div></div></div>;
}
