import type { ReleaseProposal, SemanticVector, TargetPolicy } from "./genlayer/types";

/** Preview-only fixtures. They are opt-in, visibly labelled, and never used in production. */
export const PREVIEW_ONLY_FIXTURES = {
  policy: {
    target: "0xPREVIEW_TARGET",
    owner: "0xPREVIEW_OWNER",
    project_name: "Signal Relay (preview)",
    release_constitution: "Preview only — no chain state",
    policy_fingerprint: "sha256:preview-policy",
    source_authority: "GIFTEDLOV/sentinelx",
    ci_authority: "GIFTEDLOV/sentinelx-ci",
    security_authority: "independent-reviewer-required",
    source_prefix: "https://raw.githubusercontent.com/GIFTEDLOV/sentinelx/",
    ci_prefix: "https://raw.githubusercontent.com/GIFTEDLOV/sentinelx-ci/",
    security_prefix: "https://example.invalid/independent-review/",
    current_version: "1.0.0",
    current_source_url: "https://raw.githubusercontent.com/GIFTEDLOV/sentinelx/7e3b552c8b0471db0411206fdbc743dd12ef4e80/contracts/protected_app_v1.py",
    current_code_hash: "sha256:preview-source",
    max_evidence_age_seconds: 604800,
    proposal_ttl_seconds: 86400,
    execution_timeout_seconds: 3600,
    active: true,
  } satisfies TargetPolicy,
  proposal: {
    proposal_id: 1,
    target: "0xPREVIEW_TARGET",
    proposer: "0xPREVIEW_OWNER",
    parent_version: "1.0.0",
    parent_source_url: "immutable://preview/parent",
    parent_code_hash: "sha256:preview-source",
    candidate_version: "2.0.0-safe",
    candidate_source_url: "immutable://preview/candidate",
    candidate_code_hash: "sha256:preview-candidate",
    ci_evidence_url: "immutable://preview/ci",
    ci_evidence_id: "ci-preview-1",
    security_evidence_url: "immutable://preview/security",
    security_evidence_id: "security-pending",
    evidence_set_hash: "sha256:preview-evidence",
    policy_fingerprint: "sha256:preview-policy",
    release_intent: "Add an auditable release status read.",
    created_at: Date.now() - 2 * 60 * 60 * 1000,
    expires_at: Date.now() + 22 * 60 * 60 * 1000,
    reviewed_at: 0,
    execution_deadline: Date.now() + 23 * 60 * 60 * 1000,
    status: "REVIEW_RETRY_REQUIRED",
    last_review_code: "EVIDENCE_REPAIR_REQUIRED",
  } satisfies ReleaseProposal,
} as const;

export const PREVIEW_SEMANTIC_VECTOR: SemanticVector = {
  storage_layout_compatible: true,
  public_interface_compatible: true,
  user_rights_preserved: true,
  no_privilege_escalation: true,
  upgrade_authority_preserved: true,
  consensus_integrity_preserved: true,
  finality_safety_preserved: true,
  evidence_trust_preserved: false,
  fund_flow_safe: true,
  external_fetch_surface_safe: true,
  liveness_preserved: true,
  behavioral_scope_matches_release: true,
  migration_safety_preserved: true,
  constitution_satisfied: false,
};
